apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "plngxftpbridge.fullname" . }}"
type: Opaque
stringData:
  ftp-password: {{ .Values.ftp.password }}
  paperless-password: {{ .Values.paperless.password }}
