apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ include "plngxftpbridge.fullname" . }}"
spec:
  schedule: "{{ .Values.cron }}"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
      template:
        metadata:
          name: "{{ include "plngxftpbridge.fullname" . }}"
          labels:
            app: "{{ include "plngxftpbridge.fullname" . }}"
        spec:
          serviceAccountName: {{ include "plngxftpbridge.fullname" . }}
          containers:
            - name: backup
              image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}
              env:
                - name: FTP_HOST
                  value: "{{ .Values.ftp.host }}"
                - name: FTP_USERNAME
                  value: "{{ .Values.ftp.user }}"
                - name: FTP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "plngxftpbridge.fullname" . }}
                      key: ftp-password
                - name: FTP_PATH
                  value: "{{ .Values.ftp.path }}"
                - name: PAPERLESS_URL
                  value: "{{ .Values.paperless.url }}"
                - name: PAPERLESS_USER
                  value: "{{ .Values.paperless.username }}"
                - name: PAPERLESS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "plngxftpbridge.fullname" . }}
                      key: paperless-password
          restartPolicy: OnFailure
